#MODEL:
num_classes: 2
ignore_value: 255
dino_version: 2
dinov2_size: base # Supported sizes: small, base, large
dinov3_size: base # Supported sizes: small, base, large (used when dino_version=3)
dinov3_weights_path:  # Optional explicit path to a DINOv3 weight file
dinov3_rope_dtype: bf16  # RoPE dtype for DINOv3: one of {bf16, fp32, fp16}

# FDM (Frequency Decoupling Modules)
fdm:
  enable_apm: true        # Amplitude-Phase Masker (APM)
  apm_mode: "M"           # "S" => [1,1,H,W], "M" => [1,C,H,W]
  enable_acpa: true       # Adaptive Channel Phase Attention (ACPA)

#OPTIM:
# - DINOv2：lr≈5e-4, weight_decay≈1e-4, momentum=0.9
# - DINOv3：lr≈1e-3, weight_decay≈1e-4, momentum=0.9
epochs: 200
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
clip_grad_norm: 1.0
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 10
warmup_factor: 0.1

#TRAIN:
mixed_precision: False
run: 1
RNG_seed: 0
loss_type: cross_entropy
exclude_classes: []

# High-level model/control
model_name: DINO
method: multilayer           # {linear|multilayer}
encoder_adapters: svf        # {none|lora|svf}
input_size: 512
number_of_shots: 9          # K for IFA support set selection

# IFA training defaults
use_ifa_train: true
ifa_iters: 3
ifa_refine: true
ifa_alpha: 0.3
ifa_ms_weights: [0, 0, 0.4, 0.6]
ifa_temp: 10.0
ifa_fg_thresh: 0.7
ifa_bg_thresh: 0.6
ifa_use_fdm: true
ifa_loss_w_main: 0.3
ifa_loss_w_aux: 0.0
ifa_train_support_k: 9      # Use <= number_of_shots supports each iter to save memory
ifa_detach_support: true     # Detach support features to reduce graph size

#dataset
dataset_name: disaster
split_file: datasets/disaster_1shot_splits.json
batch_size: 1 # For few-shot, batch size is often 1
train_min_size: 512
train_max_size: 512
train_crop_size: [512,512]
val_input_size: [512,512]
val_label_size: [512, 512]
aug_mode: None # Bypassing PIL-based augmentations
num_workers: 8
class_uniform_pct: 0.0
train_split: 'support' # Use the support set for training/fine-tuning
val_split: 'query'   # Use the query set for validation
max_eval: 300 # Corresponds to the query set size
eval_print_every: 10
train_print_every: 10

#checkpoint
eval_every_k_epochs: 10
eval_last_k_epochs: 5
dataset_dir : ../_datasets/Exp_Disaster_Few-Shot # Relative path to dataset
model_path : ./pretrain         # Directory containing pre-trained backbone weights
model_repo_path : ./exp/        # Directory containing local backbone repos (e.g., dinov2)
# Path to the pretrained linear decoder weights, used for methods like 'svf'
# If left empty or null, the framework will default to the current behavior.
linear_weights_path: ./exp/models_disaster/DINO_linear_disaster_100shot_run1_best.pth # Example: './exp/models_disaster/DINO_linear_disaster_10shot_run1_best.pth'
